### ISSUE TITLE
Detect Race

### ISSUE THREAD

**Issue by VincentGoins** [NCATComp410/comp410_fall_2023#10]
My part will focus on detecting an individual's race. Ex: Black, White, Hispanic, Asian.

**Comment by claesmk** [comment]
Description looks good

**Comment by ThatGuy65** [comment]
Do you have an idea on what sort of algorithm you'll use for detection? An example would be one that is based off of %.

**Comment by dawilliams5** [comment]
That is a great choice maybe you can read through and see how a person has reactions to words like black or Caucasian or Hispanic.

**Comment by KevSmoot19** [comment]
Definitely curious to see what kind of algorithm you end up using in your solution

**Comment by King-Jaden** [comment]
I wonder how an algorithm would differentiate between black the color and black the race. Phrases like African American seem easy to isolate, but white, brown, or yellow could easily be mistaken depending on the context.

**Comment by claesmk** [comment]
@VincentGoins you will run into a couple of challenges as you start working on this.  I think you will find that the default implementation will detect most racial terms as NRP (nationality, religious, or political).  It will detect Caucasian and African American but not Black or White, which is exactly the concern @King-Jaden was expressing in the comments. 

One strategy would be to create a regex based recognizer for some additional terms you might want to identify.  The reason for using a regex recognizer is you have the ability to define a score.  For example, you could implement something like this in [pii_scan.py](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L47)

```
    # create a recognizer to detect some racial terms not detected as NRP
    # https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-6-using-context-words
    race_pattern = Pattern(name="race_pattern",
                           regex='[Bb]lack|[Ww]hite',
                           score=0.01)
    race_context = ['race']
    # Define the recognizer with one or more patterns
    race_recognizer = PatternRecognizer(supported_entity="RACE",
                                        patterns=[race_pattern],
                                        context=race_context)
    # Add the recognizer to the registry
    registry.add_recognizer(race_recognizer)
```

What this does is assigns a very low score of 0.01 to any arbitrary instances of black or white, however, if the word race appears in the context the score is significantly higher (0.4) 

For example:
```
<-- spacy only results -->
text: The sky was very black
<-- Microsoft Presidio results -->
text: The sky was very black
result: black entity_type: RACE, score: 0.01, start: 17, end: 22
----------------------------------------
<-- spacy only results -->
text: Race: Black
<-- Microsoft Presidio results -->
text: Race: Black
result: Black entity_type: RACE, score: 0.4, start: 6, end: 11
----------------------------------------
<-- spacy only results -->
text: Name: John White
John White 6 16 PERSON
<-- Microsoft Presidio results -->
text: Name: John White
result: John White entity_type: PERSON, score: 0.85, start: 6, end: 16
result: White entity_type: RACE, score: 0.01, start: 11, end: 16
```

This is just one possible solution to the problem.  If you chose to go with only the terms that the NLP engine will detect by default I'm OK with that approach as well.  It's possible spacy could be retrained to add these terms, however, that is beyond the scope of this assignment.
