### ISSUE TITLE
Detecting Images Sprint 3 (Somehow..)

### ISSUE THREAD

**Issue by ThatGuy65** [NCATComp410/comp410_fall_2023#109]
Somehow performing Sprint 3 on the detect images issue

**Comment by ThatGuy65** [comment]
@claesmk Would it be best to redo what was done in sprint 2 for my code space in sprint 3? If Otherwise, what should I do to complete the Sprint? I

**Comment by ThatGuy65** [comment]
Another thing that complicates this is that the image scanner by itself will detect false positives already, so it has the false positive case handled (a false positive won't populate the array of detected images).

**Comment by ThatGuy65** [comment]
Planning to add what I have as a comment in order not further complicate the repository

**Comment by claesmk** [comment]
I'm going to help you out with this for sprint-4.  The work you did already is awesome.  I assume you read why it didn't integrate well #16 I have a few ideas for integrating it without creating all the aforementioned impacts.

**Comment by NicholasDewberryOfficial** [comment]
Hello, just updating with to let yall know #117 is approved and ready to be merged.
