### ISSUE TITLE
Correct pii_scan based on new federal inmate requirements

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_fall_2023#119]
The implementation in pii_scan was created based on the requirements defined in #38, however, #108 supersedes the original requirements.  Adapting the scanner to the latest requirements.

**Comment by trbynum** [comment]
Hi Mike, the superseding requirement is that the system identifies a number with the form xxxxx-0xx, where x is a digit from 0-9. I believe that this is consistent with my implementation in pii_scan.

**Comment by claesmk** [comment]
@trbynum please take a look at and review the changes PR #121 There were a couple of issues I corrected for you.

- Your regex was not strict enough and caused a few false positive detections.  The \b before and after avoids this.
- Your original format from #38 was still used in the scan text files. I've updated that.
