### ISSUE TITLE
Detect Gender

### ISSUE THREAD

**Issue by trinlrich** [NCATComp410/comp410_fall_2023#12]
I will be searching for gender in the given text. I will be searching for text like "Female", "Male", "Non-Binary", etc.

**Comment by claesmk** [comment]
You might find [this](https://gender-api.com) interesting, however, you will likely be limited to searching for context words in the text.  Please include what you plan to do in your description.

**Comment by AkeilaHarris** [comment]
This would be great to implement. I would suggest looking into that API claesmk comment! Excited to start working with you!

**Comment by claesmk** [comment]
@trinlrich Likely you will want to implement a [deny-list base recognizer](https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-1-deny-list-based-pii-recognition).  You can add your gender specific terms and add this as a custom recognizer in [pii_scan.py](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L47)
