### ISSUE TITLE
Detecting Citizenship/Immigration Status

### ISSUE THREAD

**Issue by AkeilaHarris** [NCATComp410/comp410_fall_2023#13]
I will be detecting citizenship/immigration status by locating it within the text. I would be looking for U.S. citizens, residents, and non-immigrant. I will be searching, for the keywords specified, in the text.

**Comment by claesmk** [comment]
Sounds good.  Can you provide some example text you would be looking for?

**Comment by AkeilaHarris** [comment]
On the form, have a section that states their citizenship. Maybe a simple question if they are e U.S citizen, and if they are not, specify if they are residents or non-immigrants.

**Comment by stormmwright** [comment]
Great idea! Will you also account for dual citizenship?

**Comment by claesmk** [comment]
@AkeilaHarris  Do you have any additional examples of the test you will be looking for?  I don't think that searching text free-form for immigration status is going to work all that well.  Likely where you would see this would be on a [customs form](https://www.cbp.gov/sites/default/files/documents/CBP%20Form%206059B%20English%20%28Sample%20Watermark%29.pdf) or a job application where that information is being requested.  
```
Residency Status

Please indicate your current residency status. This information is required to ensure compliance with employment eligibility laws and is not used to discriminate against applicants.

⬜ U.S. Citizen

⬜ Permanent Resident (Green Card Holder)

⬜ Non-Resident Alien (Requires work authorization)

⬜ Temporary Visa Holder (Please specify type: ________)

⬜ Other (Please specify: ____________________)
```

**Comment by AkeilaHarris** [comment]
@claesmk I will think of other examples of what I am looking for. I'm not sure the form you put under specifies however, that could be a format that I would locate and extract the status from. If that's not the case, I can either modify my topic or look for specific examples. Thank you!

**Comment by claesmk** [comment]
Closing this issue since switching PII focus to #74
