### ISSUE TITLE
Detect Banking Account Number 

### ISSUE THREAD

**Issue by SloaneMiller1** [NCATComp410/comp410_fall_2023#14]
My project will focus on safetyguarding and protecting Banking Account Numbers.  This will encompass account types or routing numbers depending on the feasibility of both options.  This information is vital for accessing a bank account for withdrawals, payments or similar works. 

This information is often detected in checks, online applications, or similar information for work and direct payroll. 
As such we will be checking through any of these verifiable sources and utilizing a selected system to properly secure them.

These numbers will begin with a 0,1 or 2 and be 9 digits long in total and will be detected as such.

**Comment by claesmk** [comment]
You'll need to update your description when you get a chance to explain what you'll be looking for

**Comment by claesmk** [comment]
@SloaneMiller1 - you should find that the default recognizers will do pretty well at detecting potential bank account numbers.  You should be able to write some test cases to confirm this.

**Comment by SloaneMiller1** [comment]
prefect that you so much
