### ISSUE TITLE
Detecting 12 digit MAC address

### ISSUE THREAD

**Issue by racunningham** [NCATComp410/comp410_fall_2023#18]
My part will detect MAC addresses (12 digit hexadecimal number) in the form of:

xx:xx:xx:xx:xx:xx

**Comment by claesmk** [comment]
Looks good

**Comment by tolanism** [comment]
Thats cool! You could test for incorrect entries - character recognized that would invalidate the address.

**Comment by claesmk** [comment]
That's correct @tolanism - for sprint-2 both a positive and a negative test will be expected

**Comment by claesmk** [comment]
@racunningham you should be able to use [uuid](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L50) detection as an example for what you are trying to do with a MAC address.
