### ISSUE TITLE
Detecting 16 Digit Credit Card Numbers

### ISSUE THREAD

**Issue by mdpaylor** [NCATComp410/comp410_fall_2023#2]
Implement Detection for 16-digit credit card numbers.

This includes detection of “XXXX XXXX XXXX XXXX,” “XXXX-XXXX-XXXX-XXXX,” etc. Any sequence of numbers that are separated by some delimiter. This rules out values with no space between each sequence of 4 characters.

Example: 1234 5678 9012 3456

16 Digit Credit Card numbers are essential to the world as we know it. The breaching of credit card numbers along with the respective Card Security Code (CSC) and the expiration date could cause many major fraud issues.

To avoid false detection of “credit card numbers” (even though the ones used for testing will be fake), [Luhn’s Algorithm](https://www.ibm.com/docs/da/order-management-sw/9.3.0?topic=cpms-handling-credit-cards) will be used. This algorithm basically states to sum all of the numbers but to take every other value from right to left, starting with the second to last digit, and double each one. If a number is over 10, add the sum of the 2 digits to the other numbers calculated. The credit card number should be legitimate if the total sum modulo 10 is 0.

**Comment by claesmk** [comment]
You need to add a description.  Why are there two people assigned to this @KidSens @mdpaylor

**Comment by mdpaylor** [comment]
It has been taken care of. I was working on the description @claesmk.

**Comment by claesmk** [comment]
OK - looks good - you might find [this](https://developer.squareup.com/docs/devtools/sandbox/payments) helpful for coming up with some test credit card number

**Comment by claesmk** [comment]
@mdpaylor after you review the instructions for Sprint2 and begin working on your issue I think you will find that the default [Presidio credit card recognizer](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/predefined_recognizers/credit_card_recognizer.py) will work pretty well for you.  It has also implemented Luhn's algorithm.  You should be able to focus on creating some good positive and negative test cases to see how well it works.
