### ISSUE TITLE
Detect Place of Birth

### ISSUE THREAD

**Issue by Kgeddis** [NCATComp410/comp410_fall_2023#27]
I will be detecting Place of Birth in the format of "city name, state acronym" Example: Greensboro, NC
I will look for keywords such as "place of birth"," "POB", "birthplace".
Protecting one's place of Birth is crucial because place of birth is an important aspect to one's identity. Someone's place of Birth can tell us a lot about their background and combined with other PII we can find out a lot about this person. Also a person's birthplace is often used for verification purposes and if it is compromised, it can be used for identity theft, financial fraud, and other types of threats to their personal privacy.
I can scan various documents to find this information.

**Comment by claesmk** [comment]
Description looks OK.  I would also recommend using POB, born, and birthplace, in your context words.

**Comment by Aaronb0117** [comment]
Good description. could you possibly add more context.

**Comment by mjonesncat** [comment]
Expand on the importance of protecting a person's place of birth and what problems could occur if it is not protected. A person's birthplace is often used for verification purposes and if compromised, it can be used for identity theft, financial fraud, and other types of threats to your personal privacy.

**Comment by claesmk** [comment]
@Kgeddis this will be a little more difficult to implement than some other types of PII. One strategy would be to allow the default recognizer to detect locations and add a custom recognizer to detect your place of birth terms.  If you follow the [example](https://microsoft.github.io/presidio/tutorial/01_deny_list/) your custom recognizer (which should go in [pii_scan.py](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L47)) might look something like this:
```
    # Create a recognizer to detect place of birth
    place_of_birth_terms = ['place of birth', 'birthplace', 'born']
    pob_recognizer = PatternRecognizer(supported_entity="POB", deny_list=place_of_birth_terms)
    registry.add_recognizer(pob_recognizer)
```

Then you would end up with both the place of birth and location in your results.  For example, here is the difference between someone who lives in Greensboro and someone who was born in Greensboro

```
Enter a test string or <enter> to quit: I live in Greensboro, NC
<-- spacy only results -->
text: I live in Greensboro, NC
Greensboro 10 20 GPE
NC 22 24 GPE
<-- Microsoft Presidio results -->
text: I live in Greensboro, NC
result: Greensboro entity_type: LOCATION, score: 0.85, start: 10, end: 20
result: NC entity_type: LOCATION, score: 0.85, start: 22, end: 24
----------------------------------------
Enter a test string or <enter> to quit: I was born in Greensboro, NC
<-- spacy only results -->
text: I was born in Greensboro, NC
Greensboro 14 24 GPE
NC 26 28 GPE
<-- Microsoft Presidio results -->
text: I was born in Greensboro, NC
result: born entity_type: POB, score: 1.0, start: 6, end: 10
result: Greensboro entity_type: LOCATION, score: 0.85, start: 14, end: 24
result: NC entity_type: LOCATION, score: 0.85, start: 26, end: 28
```

In your test case you would look for the presence of POB and LOCATION separately, for example:
```
        # Positive test case
        results = analyze_text('I was born in Greensboro, NC')
        # expect LOCATION to be detected
        self.assertIn('LOCATION', str(results))
        # expect POB to be detected
        self.assertIn('POB', str(results))
        
        # Negative test case
        results = analyze_text('I live in Greensboro, NC')
        # expect LOCATION to be detected
        self.assertIn('LOCATION', str(results))
        # expect POB to be detected
        self.assertNotIn('POB', str(results))
```
