### ISSUE TITLE
Detecting Political opinions

### ISSUE THREAD

**Issue by dawilliams5** [NCATComp410/comp410_fall_2023#28]
My project will detect the political opinions of someone by searching if they have strong opinions one way or the other. This should stay anonymous because if known of a person political opinion then ideas can be easily planted in this persons head by using selective keywords. his project will work by searching for key words in their conversation like:
"liberals"
"democrats"
"republicans"

**Comment by claesmk** [comment]
Description looks good

**Comment by ashadixon** [comment]
I like this topic for your project. This is interesting and I'm excited to see it flourish.

**Comment by trbynum** [comment]
This is a really good topic for your project. Will your system be able to detect third-party political parties like Libertarian, Green, Socialist, etc.?

**Comment by KevSmoot19** [comment]
> 

This is a good question, I'm curious as well and look forward to seeing how your project plays out.

**Comment by claesmk** [comment]
@dawilliams5 you will find that the default recognizers will detect some terms for you, such as democrat or republican.  If this is not good enough, you can follow the [example](https://microsoft.github.io/presidio/tutorial/01_deny_list/) to add a new list of terms you'd like to add.
