### ISSUE TITLE
Detect Full Names

### ISSUE THREAD

**Issue by mjonesncat** [NCATComp410/comp410_fall_2023#29]
Implement Detection for Full Names 

I want to implement a solution for detecting full names, including first, middle, and last names, within text data. Detecting full names is valuable for various applications, but it must be done carefully to respect privacy and security concerns. I will use a regular expression pattern which will be designed to match full names that start with a capitalized first name, followed by zero or more middle names with each following the same pattern as the first name, and an optional suffix. I will also use word boundary anchors to ensure that I am matching whole names within the text.

Example:
Joseph Michael Johnson

 I must keep in mind that full names can vary in structure and format, and this pattern may not cover all possible variations. Therefore, depending on the specific context and data I work with, I may need to customize the pattern further to accommodate different naming conventions or cultural variations.

**Comment by Lesterconey** [comment]
Add the milestone "Sprint-1" so you are able to keep track of your progress. Also, it might be good to assign this issue to yourself.

**Comment by Kgeddis** [comment]
You should also include how you will have to check for capitalization . For example if the whole name is in all caps, or if only the first letter of the name is capitalized , or is every letter in the name lower case.

**Comment by claesmk** [comment]
Description looks good, however, I think you will be limiting yourself if you rely on regex alone.  For example, "Mount Washington" would get detected as a name.  You'd also miss a hyphenated name such as Jane Jones-Smith.  

In the sprint-2 instructions we'll be introducing the [Presidio](https://microsoft.github.io/presidio/) SDK which will help with PII detection. 

I don't think you should try to implement name detection for cases where the name is all caps.  Re-training an NLP model is beyond the scope of this class and I know for a fact that the default spacy [models](https://spacy.io/models/en) will not detect this.

**Comment by Aaronb0117** [comment]
You also add that there must be an understanding of the potential variations in name structures across different contexts and cultures. Using a well-designed regular expression pattern with word boundary anchors is a good starting point, but flexibility to adapt the pattern as needed is crucial to ensure accurate recognition of full names in diverse text data.
