### ISSUE TITLE
Detect Dates of Birth 

### ISSUE THREAD

**Issue by tolanism** [NCATComp410/comp410_fall_2023#3]
Detect number birthdates 

able to detect the following formats of birthdates:

mm/dd/yy , mm/dd/yyyy , dd/mm/yy , dd/mm/yyyy 

valid dates with digits 0-9

detecting number dates only

**Comment by tfortobi** [comment]
The last date format could be d/m/yy

**Comment by tolanism** [comment]
> The last date format could be d/m/yy

Good idea! thank you

**Comment by jenniferibe** [comment]
Great idea! However, I think you should add a description to give us a better sense of your concept!

**Comment by claesmk** [comment]
@tolanism I think you will find that Presidio does pretty well at detecting dates, however, it does not have any default implementations for date of birth. Likely you'll want to look at this [example](https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-6-using-context-words) for creating a custom analyzer and you'll want to use some context words such as DOB, birth, etc, to do what you want.

**Comment by claesmk** [comment]
We decided on this solution 
```
    birthdate_pattern = Pattern(name='birthdate_pattern',
                                regex=r'\b(0[1-9]|[1-3][0-9])/(0[1-9]|[12][0-9]|3[01])/(\d{4}|\d{2})\b',
                                score=0.4)
```
