### ISSUE TITLE
Detect Eye Color

### ISSUE THREAD

**Issue by Lesterconey** [NCATComp410/comp410_fall_2023#30]
I will detect eye color within text because it is PII information. I will be able to parse a sentence and figure out if it contains an eye color. Some examples would be, "Brown eyes", "Blue eyes", "Eyes that are green".

**Comment by claesmk** [comment]
I think this is too similar to #10 so marking it as a duplicate.  Please either pick a different PII topic or work with @VincentGoins to clearly differentiate how these two issues are different.

**Comment by Lesterconey** [comment]
> I think this is too similar to #10 so marking it as a duplicate. Please either pick a different PII topic or work with @VincentGoins to clearly differentiate how these two issues are different.

I've addressed your comment and changed my topic to a different type of PII.

**Comment by claesmk** [comment]
Probably a better example would be a form that someone fills out
```
Eye Color: Brown 
```

**Comment by claesmk** [comment]
@Lesterconey I think you can use either a custom [regex](https://microsoft.github.io/presidio/tutorial/02_regex/) or a [deny list ](https://microsoft.github.io/presidio/tutorial/01_deny_list/) recognizer to look for "eye color" as I suggested above
