### ISSUE TITLE
Detecting philosophical beliefs

### ISSUE THREAD

**Issue by tfortobi** [NCATComp410/comp410_fall_2023#31]
Implement detection of philosophical beliefs.

Philosophical beliefs are non-religious beliefs. These are strong and genuine beliefs that are important aspects of human life and behavior. If this information is not protected it can cause discrimination due to certain beliefs. Some beliefs are not supported by all, and this could create other problems in one's life.

Examples: humanism, secularism, and atheism

Must keep in mind that there is a difference between these beliefs and religious beliefs.

**Comment by claesmk** [comment]
Description looks good.  I ran a quick test to see if spacy detects any of these words.  You can see it recognized the religions but not the philosophical beliefs. 
```
text: catholic, christian, jewish, muslim, hindu, buddhist, atheist, agnostic, humanism, secularism
<-- terms detected -->
catholic 0 8 NORP
christian 10 19 NORP
jewish 21 27 NORP
muslim 29 35 NORP
hindu 37 42 NORP
buddhist 44 52 NORP
```

**Comment by tfortobi** [comment]
Should I change what I am trying to detect?

**Comment by claesmk** [comment]
I think your idea is fine.  As you can see the default detector will not find the words you are looking for so it will not overlap with anyone else's work
