### ISSUE TITLE
Detect Interests

### ISSUE THREAD

**Issue by Caleb-Andrew-Mitchell** [NCATComp410/comp410_fall_2023#32]
I want to detect what people are interested in. It will detect hobbies such as dancing, playing baseball or reading. As well as subjects the user likes researching about like Chris-Chan or Bibleman. 

- Caleb Mitchell
Team: Hackitects
Milestone: Sprint 1

**Comment by chelseavuata** [comment]
You forgot to include your assignment to yourself, your team, and the milestone which is "Sprint 1".

**Comment by claesmk** [comment]
Your description is pretty broad.  I would suggest narrowing the scope to a specific sport.  For example, a common "forgotten password reset" question is favorite sports team.

**Comment by Caleb-Andrew-Mitchell** [comment]
> Your description is pretty broad. I would suggest narrowing the scope to a specific sport. For example, a common "forgotten password reset" question is favorite sports team.

Thank you for your input. I will update my description.

**Comment by claesmk** [comment]
@Caleb-Andrew-Mitchell you have not accepted your invitation to join the class team.  If you missed the email you should be able to see the invitation from this [link](https://github.com/orgs/NCATComp410/invitation)

**Comment by Caleb-Andrew-Mitchell** [comment]
> @Caleb-Andrew-Mitchell you have not accepted your invitation to join the class team. If you missed the email you should be able to see the invitation from this [link](https://github.com/orgs/NCATComp410/invitation)

Thank you. I've just accepted the invitation.
