### ISSUE TITLE
Detect Unique Device Identification Number

### ISSUE THREAD

**Issue by chelseavuata** [NCATComp410/comp410_fall_2023#33]
Implement detection of UDID (Unique Device Identification Number)

A unique device identification number (focusing on Apple devices) is found on every Apple device. It identifies a specific device for debugging, app installation, and mobile tracking. 

It is a 24-digit sequence of letters A-F and numbers 0-9 which can be used for detection.

Example: A638F54E-F6E82B43C580E24F

**Comment by claesmk** [comment]
This is a duplicate of #1 please pick a different PII topic

**Comment by claesmk** [comment]
@chelseavuata please provide an example ID that you will use for testing.  Please make sure it isn't a valid one.  In the future when you have duplicated an issue it is better to close the issue and create a new one.  This makes the audit history easier to follow.

**Comment by tfortobi** [comment]
Yea, an example UDID would be good.
