### ISSUE TITLE
Detecting International Phone Numbers

### ISSUE THREAD

**Issue by ashadixon** [NCATComp410/comp410_fall_2023#34]
PII represents information that can directly correlate to the users. Phone numbers are considered PII. I chose International Phone Numbers because it is important to recognize anyone's information can be found. 

An international phone number is a number that starts with the code for a particular country.

A common way of detecting the number is: XX-(0)XX-XXX-XXXX or XX-(0)XX-XXXX-XXXX

**Comment by claesmk** [comment]
Description looks good
