### ISSUE TITLE
Detecting Credit/ Debit Card Number

### ISSUE THREAD

**Issue by Vgoods** [NCATComp410/comp410_fall_2023#35]
Detect sequence number of credit/ debit card number, expiration date, CVV, and card type

Able to detect the following formats for number sequence:

Card Number- xxxx xxxxxx xxxxx 

Valid Numbers in sequence past  .9

Detect the type of card by first number in card number sequence:

American Express- 3

Able to detect expiration date under format:

Expiration Date- ##/##

Valid date past .9

Able to detect CVV under format:

CVV- ###

Valid number sequence past .9

**Comment by rdouglas202** [comment]
You could also detect the expiration date and CVV of the number as well since it's within your scope.

**Comment by Vgoods** [comment]
> You could also detect the expiration date and CVV of the number as well since it's within your scope.

That’s a good point, I could also differentiate between master card, visa, American express, etc.

**Comment by mjonesncat** [comment]
Add the milestone "Sprint-1" so you are able to keep track of your progress.

**Comment by claesmk** [comment]
@Vgoods As written this is a duplicate of #2 if you want to work with @mdpaylor perhaps they could focus on the xxxx xxxx xxxx xxxx pattern and you could focus on AMEX

**Comment by Vgoods** [comment]
Ok I will message them.

**Comment by mdpaylor** [comment]
That sounds good to me @claesmk @Vgoods

**Comment by claesmk** [comment]
Alright @Vgoods please update your issue to focus on amex - there are some great references [here](https://developer.squareup.com/docs/devtools/sandbox/payments)

Plan to focus on xxxx xxxxxx xxxxx for example 3400 000000 00009

**Comment by Vgoods** [comment]
Thanks for the tip, I will change that ASAP.
