### ISSUE TITLE
Detecting Health Insurance Policy Number

### ISSUE THREAD

**Issue by jewelworks** [NCATComp410/comp410_fall_2023#37]
Detecting health insurance policy numbers by having the user enter their Health Care provider. I will then have them enter their 12-digit policy number to identify the user.
For example, if the user enters Blue Cross they will enter their policy ID # XYZ123456789.

**Comment by claesmk** [comment]
Description looks OK.  How are you planning to make sure you don't use a real policy ID during testing?
