### ISSUE TITLE
Detecting Federal Inmate Numbers

### ISSUE THREAD

**Issue by trbynum** [NCATComp410/comp410_fall_2023#38]
I will design a system that can identify valid 8-digit federal prison inmate numbers. The system will be built to detect numbers from 00000000 to 99999999.

**Comment by mjonesncat** [comment]
In your description, you should emphasis why protecting federal inmate numbers is important and what could occur if this type of personal information is stolen.

**Comment by claesmk** [comment]
How do you plan to make sure you don't use a valid ID during testing?

**Comment by Kgeddis** [comment]
In your description you should add why scanning for this information could be useful.
