### ISSUE TITLE
Detecting Social Media Username

### ISSUE THREAD

**Issue by Jordanwhit1** [NCATComp410/comp410_fall_2023#40]
Able to detect social media usernames preceeded by the '@' symbol.

Usernames should be able to have characters 0-9, A-Z, or a-z in any combination not to exceed 16 characters not including the '@'.

Usernames may contain non numeric or alpha characters such as '_' '-' but not characters outside of these.

**Comment by claesmk** [comment]
@Jordanwhit1 this looks good.  Please make sure to add your team label.

**Comment by SloaneMiller1** [comment]
You've done an excellent job developing your idea and content research to ensure you pull the correct information. It might be helpful to be capable of specifying which social media username you're looking for; that way, you can apply that site's exact rules and adjust for every additional site.
