### ISSUE TITLE
Detect IPv4 Addresses

### ISSUE THREAD

**Issue by KevSmoot19** [NCATComp410/comp410_fall_2023#5]
I will be implementing a detection of IPv4 addresses.

IPv4 address are in the format of x.x.x.x where 'x' can be any number between 0-255. For example, a valid IPv4 address would be 123.456.78.90. My code will test each 'x' and ensure that the number is between 0 and 255, or else it will be marked as invalid.

IP addresses are unique and can be used to identify any and every device and/or network that connects to the internet.

**Comment by claesmk** [comment]
You need to add a description

**Comment by claesmk** [comment]
@KevSmoot19 reminder to add your description

**Comment by racunningham** [comment]
In case you hadn't already thought of it, you could consider doing IPv4 and IPv6.

**Comment by KevSmoot19** [comment]
Forgot to reflection my specific choice in the title, but I updated it and the description now. Thanks for pointing that out @racunningham

**Comment by claesmk** [comment]
@KevSmoot19 I think you will find that the default recognizer will detect IP addresses pretty well.

**Comment by KevSmoot19** [comment]
Due to delayed reviews of some of the commits on my last PR, I had complications with building files in preparation to merge. So I have deleted the branch and code space. I am now creating a new branch, code space, and shortly a new PR.
