### ISSUE TITLE
SPNT 2 - What files do we end up modifying/ what files shouldn't we (also more general questions)

### ISSUE THREAD

**Issue by NicholasDewberryOfficial** [NCATComp410/comp410_fall_2023#54]
Good afternoon. I assembled my team for us to get this project out of the way. We've made some good progress, however we have some scuffed stuff. 

1. Should we have our own pull requests? 
Our team has one on https://github.com/NicholasDewberryOfficial/TeamHackitectsFork-410

2. Should everyone on our team work in the same codespace? 
We're all in one codespace and working there. I've been using microsoft liveshare to edit files

3. What files do we edit?
I've been editing the test_team_hackitects.py file (which i think we're supposed to do), do we also edit the analyze_text file? 

4. Do we write our test cases in plain text, or do we need to read from a file? 
Looking through some other code examples, that's what team_null did. Can we do it too? I know we will be reading from a file in the future, should we start now

I got more questions and things to write, ill add more later. pls respond when u get the chance @claesmk

**Comment by claesmk** [comment]
The intent of the assignment is for each developer on the team to gain experience by working on their issue from their own codespace.  I show how to create a development branch for each issue at 3:20 in the instructions video. This does not require any forking.

I discuss using your team unit test file around 13:00 in the video - you will put all your test cases into test_team_hackitects.py.  If you want to read data from files, you can, however that is not a requirement. 

One [issue](https://github.com/NCATComp410/comp410_fall_2023/issues/16) for photo detection  is particularly difficult and will require extensive additional work.

Some [issues](https://github.com/NCATComp410/comp410_fall_2023/issues?q=is%3Aopen+is%3Aissue+label%3A%22Team+Hackitects%22) will require adding code to the analyze_text() function in pii_scan.py, others will require different solutions. 

I would recommend continuing the discussions in each individual [issue](https://github.com/NCATComp410/comp410_fall_2023/issues?q=is%3Aopen+is%3Aissue+label%3A%22Team+Hackitects%22) for guidance on specific issue implementations.

**Comment by NicholasDewberryOfficial** [comment]
Thanks! I wasn't sure. All of us have gotten quite a bit of codespace experience from all of this. 

On a separate note, over inside my [repository ](https://github.com/NicholasDewberryOfficial/TeamHackitectsFork-410/blob/main/test_team_hackitects.py) I have managed to get my tests working. One problem tho: I imported a python 3 regex package, then used that for my tests. 

Is that alright? Or do we have to use the microsoft presidio SDK? 


![image](https://github.com/NCATComp410/comp410_fall_2023/assets/85315604/5b51cdc7-cd9b-4d03-8992-7a4b825a0d3d)

**Comment by NicholasDewberryOfficial** [comment]
The code that I sent didn't properly do what we needed. [This is more up-to-date. 
](https://github.com/NicholasDewberryOfficial/TeamHackitectsFork-410/blob/main/test_team_hackitects.py)

![image](https://github.com/NCATComp410/comp410_fall_2023/assets/85315604/f69ba385-1af5-45e5-be66-4ae25d4fb6f6)

**Comment by claesmk** [comment]
As we discussed in #7 the default recognizers do a pretty good job of at least identifying your street address as a LOCATION
```
<-- Microsoft Presidio results -->
text: 1601 E Market St, Greensboro, NC 27411
result: Greensboro entity_type: LOCATION, score: 0.85, start: 18, end: 28
result: NC 27411 entity_type: LOCATION, score: 0.85, start: 30, end: 38
```
If you aren't happy with these results and you want to add a custom regex you should do that in [analyze_text](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L36) similar to what was done for a [uuid](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L50) and the associated [testcase](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/test_pii_scan.py#L17).  

I would expect a test case for you issue to look something like this:
```
    def test_address(self):
        # test a valid street address
        results = analyze_text('1601 E Market St, Greensboro, NC 27411')
        self.assertIn('LOCATION', str(results))
        # test an invalid street address
        results = analyze_text('1601 Nowhere')
        self.assertNotIn('LOCATION', str(results))
```

**Comment by NicholasDewberryOfficial** [comment]
Thanks! 

For addresses, is it alright if I include public university addresses, or did you want me to only have fictional ones?
