### ISSUE TITLE
Identify American Address (in text)

### ISSUE THREAD

**Issue by NicholasDewberryOfficial** [NCATComp410/comp410_fall_2023#7]
Sprint 1
Milestone 1 

I want to implement something to analyze if if an American address is detected. It's EXTREMELY important to protect addresses from being found by anyone in the internet. You could have simple trolling, like ordering pizzas to someones house to dangerous harrasment like the Swatting trend (calling the FBI or 
a police department with a hoax that someone has a bomb/someone is committing murder, examples are seen: https://en.wikipedia.org/wiki/Swatting) seen in recent years. 

Example: 
1601 E Market St, Greensboro, NC 27411

Format is (Street number) Street name [optional apartment number] [City name, zip code] [optional country]

This will be a bit tough, but a welcome challenge. There's a lot of moving parts, and I'd like to make it work.

**Comment by claesmk** [comment]
Description looks good.  You need to add a label with your team name

**Comment by NicholasDewberryOfficial** [comment]
> Description looks good. You need to add a label with your team name

Members of my team cannot add labels. We should have a gear icon on the right side that would let us customize our issue, however it is missing. I think it may be because we took some time to email our Github IDs 


![image](https://github.com/NCATComp410/comp410_fall_2023/assets/85315604/215144dd-8aa2-4917-9f87-3aa7169bb256)

**Comment by claesmk** [comment]
@NicholasDewberryOfficial several individuals have not accepted the invitation from GitHub to join the repo yet.  Sometimes the email goes to spam folder.  Encourage everyone to check their personal GitHub [dashboard](https://github.com/dashboard) to look for the invitation and also check which email address it would have gone to.

**Comment by ThatGuy65** [comment]
Seeing as there are many ways to write an address, do you think it would be helpful to have some regex implementation for detection?

**Comment by NicholasDewberryOfficial** [comment]
> @NicholasDewberryOfficial several individuals have not accepted the invitation from GitHub to join the repo yet. Sometimes the email goes to spam folder. Encourage everyone to check their personal GitHub [dashboard](https://github.com/dashboard) to look for the invitation and also check which email address it would have gone to.

Thanks. I clicked the invite and now I'm able to add labels.

**Comment by NicholasDewberryOfficial** [comment]
> @NicholasDewberryOfficial what happened here? It looks like it was moved to the wrong project and then closed? The issue should remain open until the code has been added

Oh sorry. I wasn't sure. I thought I could close it. My bad.

**Comment by mthorn12** [comment]
This looks good! For the example you used just make sure your code can detect and identify abbreviations. 1601 E Market St, Greensboro, NC 27411 is the same as 1601 East Market Street, Greensboro, North Carolina 27411.

**Comment by claesmk** [comment]
@NicholasDewberryOfficial I think you will find this is a little tricky to implement. The default recognizers will do a pretty good job at detecting some things you are looking for, however, you'll need to experiment to see what else you might like to try to catch.  The have an [example](https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-6-using-context-words) for implementing a zip code. No NLP detection is perfect and you'll have to decide what is good enough for you.
```
<-- spacy only results -->
text: 1601 E Market St, Greensboro, NC 27411
1601 0 4 CARDINAL
Greensboro 18 28 GPE
NC 27411 30 38 FAC
<-- Microsoft Presidio results -->
text: 1601 E Market St, Greensboro, NC 27411
result: Greensboro entity_type: LOCATION, score: 0.85, start: 18, end: 28
result: NC 27411 entity_type: LOCATION, score: 0.85, start: 30, end: 38
```

**Comment by NicholasDewberryOfficial** [comment]
> @NicholasDewberryOfficial I think you will find this is a little tricky to implement. The default recognizers will do a pretty good job at detecting some things you are looking for, however, you'll need to experiment to see what else you might like to try to catch. The have an [example](https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-6-using-context-words) for implementing a zip code. No NLP detection is perfect and you'll have to decide what is good enough for you.
> 
> ```
> <-- spacy only results -->
> text: 1601 E Market St, Greensboro, NC 27411
> 1601 0 4 CARDINAL
> Greensboro 18 28 GPE
> NC 27411 30 38 FAC
> <-- Microsoft Presidio results -->
> text: 1601 E Market St, Greensboro, NC 27411
> result: Greensboro entity_type: LOCATION, score: 0.85, start: 18, end: 28
> result: NC 27411 entity_type: LOCATION, score: 0.85, start: 30, end: 38
> ```

Thanks for looking into it and seeing potential outcomes. I was planning on being VERY strict with spaces/commas, while being more open with the optional sections. I've made quite a few string parsers/lexical analyzers in the past (Instead of using bools, I've made video games in the past where everything is in a string form. It was stupid, but I learned a lot about how to iterate through strings on a conceptual level. ).

I've dipped my toes into regex analysis at a past job I've had (it was for firewall/file stuff), and I was hoping I could go into it more here. I've got some free time this Saturday, I'll get ahead of this project to see how everything goes. I don't like their example, because I was hoping I could just look at any 5 digit string of numbers and call it a day for the zip section - but thanks for bringing it up to me.

**Comment by claesmk** [comment]
Just for fun, I asked ChatGPT to generate 1,000 random addresses and I checked what the default analyzer returned.  The majority were detected as either a LOCATION or an ORGANIZATION, however, Eldertown was an outlier.
```
Enter a test string or <enter> to quit: 3128 Spruce Dr., Eldertown, CA 76455
<-- spacy only results -->
text: 3128 Spruce Dr., Eldertown, CA 76455
3128 0 4 CARDINAL
Eldertown 17 26 PERSON
<-- Microsoft Presidio results -->
text: 3128 Spruce Dr., Eldertown, CA 76455
result: Eldertown entity_type: PERSON, score: 0.85, start: 17, end: 26
```

I pushed this example to the [address_test](https://github.com/NCATComp410/comp410_fall_2023/tree/address_test) branch.  I hacked up pii_scan.py to read the list of addresses. This was pretty encouraging considering all of NLP's limitations.  

Will be interesting to see what you come up with.  I also have a regex I like to use, which I also ran on the ChatGPT data, and I got a 100% success rate.  However, I'm sure there are some weird addresses that nothing will detect correctly.

**Comment by claesmk** [comment]
@NicholasDewberryOfficial just in case the discussion in #54 wasn't clear, the development process I would suggest for this issue is the same as shown in the video:

(1) You should create your development branch and codespace as shown in the video.  If you want to do it a different way, you can, as long as you are comfortable doing so. 

(2) You should use [spacy_vs_ms.py](https://github.com/NCATComp410/comp410_fall_2023/blob/main/spacy_vs_ms.py) to first see what the default recognizers will do, in your case, you'll get a LOCATION
```
<-- Microsoft Presidio results -->
text: 1601 E Market St, Greensboro, NC 27411
result: Greensboro entity_type: LOCATION, score: 0.85, start: 18, end: 28
result: NC 27411 entity_type: LOCATION, score: 0.85, start: 30, end: 38
```
(3) Starting from here you can now create your test case (in test_team_hackitects.py)
```
    def test_address(self):
        # test a valid street address
        results = analyze_text('1601 E Market St, Greensboro, NC 27411')
        self.assertIn('LOCATION', str(results))
        # test an invalid street address
        results = analyze_text('1601 Nowhere')
        self.assertNotIn('LOCATION', str(results))
```
If you want, you can stop here and proceed with your pull request and code review - you would now be successfully detecting a street address as a LOCATION - which at least meets your issue requirements.  This is also an example of a positive and a negative test case. 

(4) If you want to use your own custom regex you could create a different entity similar to the [uuid](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L50) example.  This would look something like this (I included the uuid example from pii_scan.py for clarity so you can see where you would add your regex and code)
```
    # Custom recognizers
    # https://microsoft.github.io/presidio/analyzer/adding_recognizers/
    # Create an additional pattern to detect a 8-4-4-4-12 UUID
    uuid_pattern = Pattern(name='uuid_pattern',
                           regex=r'\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b',
                           score=0.9)
    uuid_recognizer = PatternRecognizer(supported_entity='UUID',
                                        patterns=[uuid_pattern])
    registry.add_recognizer(uuid_recognizer)

    # Add a custom pattern to detect a street address
    street_pattern = Pattern(name='street_pattern',
                           regex=r'[0-9]+\s[A-Za-z]+\s[A-Za-z]+\s[A-Za-z]+,\s[A-Za-z]+,\s[A-Za-z][A-Za-z]\s\d\d\d\d\d',
                           score=0.9)
    street_recognizer = PatternRecognizer(supported_entity='STREET_ADDRESS',
                                        patterns=[street_pattern])
    registry.add_recognizer(street_recognizer)
```
You would then modify your test case accordingly to look for a STREET_ADDRESS entity instead of a LOCATION

If you chose to use this regex I think you will find that it is not generic enough to match the additional street addresses that ChatGPT came up with, which will be an issue for you in sprint-3
