### ISSUE TITLE
Sprint 2 problem

### ISSUE THREAD

**Issue by Jagantt004** [NCATComp410/comp410_fall_2023#72]
Hello, I just had a question about sprint 2. All the test cases failed when I ran them for the first time and in the video, I didn't see how to fix this or if this affected my the way I did the assignment.

**Comment by AkeilaHarris** [comment]
Hi, I am having the same issue.

**Comment by claesmk** [comment]
@Jagantt004 @AkeilaHarris I reverted #79 because it was causing a couple of unintentional side effects including test failures

**Comment by claesmk** [comment]
Closing this issue since the revert mentioned above seems to have resolved issues
