### ISSUE TITLE
Detect NC Drivers License  

### ISSUE THREAD

**Issue by mthorn12** [NCATComp410/comp410_fall_2023#8]
This will detect 12 digit drivers license for residents of NC. It is important to protect DL number because it can be used to commit identity fraud.

**Comment by claesmk** [comment]
You need a description and also add a label with your team name

**Comment by NicholasDewberryOfficial** [comment]
Good idea. Would the state where the drivers license was taken from matter at all?

**Comment by claesmk** [comment]
@mthorn12 reminder you still need to add a description 

You might find this [link](https://ntsi.com/drivers-license-format/) helpful for state specific information

**Comment by claesmk** [comment]
@mthorn12 - The ID you provided to Dr Hinton was mthron12.  I corrected the error and sent you an invite.  This is why you were not able to add a label to your issue.  If you missed the email invitation you should be able to see it [here](https://github.com/orgs/NCATComp410/invitation).

**Comment by mthorn12** [comment]
> @mthorn12 reminder you still need to add a description
> 
> You might find this [link](https://ntsi.com/drivers-license-format/) helpful for state specific information

Should I try to do all 50 states or do you think that would be too much?

**Comment by claesmk** [comment]
We'll see how it goes when you implement this.  You can always expand your goal to detect a US driver's license.  Have you thought about how you will avoid using a valid driver's license during testing?

**Comment by claesmk** [comment]
@mthorn12 After you review the sprint instructions I think you'll find the default recognizers do a pretty good job at detecting potential driver's license numbers. You can write some test cases to make sure.

**Comment by claesmk** [comment]
@mthorn12 @NicholasDewberryOfficial My first question is why aren't the [default recognizers](https://microsoft.github.io/presidio/supported_entities/) for US_DRIVER_LICENSE detecting an NC driver's license?

**Comment by claesmk** [comment]
@mthorn12 @NicholasDewberryOfficial I pushed a few suggestions to your development branch for the regex and also the name for your recognizer.  If you are trying to find just a 12-digit NC driver's license then how about using NCDL for an entity?

**Comment by mthorn12** [comment]
> @mthorn12 @NicholasDewberryOfficial I pushed a few suggestions to your development branch for the regex and also the name for your recognizer. If you are trying to find just a 12-digit NC driver's license then how about using NCDL for an entity?

My code won't commit at all. Is there any way to meet with you to resolve this issue.

**Comment by claesmk** [comment]
@mthorn12 Dr Hinton created some office hours for 8:30pm tonight Nov-15th.  Can you make that work?

**Comment by claesmk** [comment]
#103
