### ISSUE TITLE
Sprint 2 - Detect drivers license bug - Extension required

### ISSUE THREAD

**Issue by NicholasDewberryOfficial** [NCATComp410/comp410_fall_2023#89]
Hello, I've been working with @mthorn12 to solve her drivers license issue

The main problem comes down to how she has a regex that detects 12 digits - but it fails in her tests. 

This is a problem because online, when she runs her regex - it works perfectly fine. However when she runs it on microsoft presidio, it causes an error. 

We'd like another day or 2 to solve this. 

including the "bug" label because it literally works online and with normal regex, but somehow fails here. No clue why.

**Comment by claesmk** [comment]
Linking this to #8 and closing.  We can either create a PR and solve the issue there or discuss it further in #8
