### ISSUE TITLE
Detect E-mail Addresses

### ISSUE THREAD

**Issue by Aaronb0117** [NCATComp410/comp410_fall_2023#9]
My part will focus on detecting an individual's e-mail address. with format @-----.com, and @----.edu.  ex:  @gmail.com, @hotmail.com,@aggies.ncat.edu, etc. E-mail address have certain valid characters which are alphanumeric characters and not characters like "$", "&" etc. They also have a max character length of 320 characters. I will use these limits to calculate a valid e-mail address.

**Comment by claesmk** [comment]
Your description needs more detail such as the format for an email address, valid characters, length, etc.

**Comment by Kgeddis** [comment]
You should add how the email can only contain alphanumeric characters and not characters like "$", "&" etc.

**Comment by mjonesncat** [comment]
Give a short description of why precise detection and protection of email addresses is so important to maintaining personal privacy.

**Comment by claesmk** [comment]
Are you sure about the max character length?  [Reference](https://en.wikipedia.org/wiki/Email_address)

**Comment by claesmk** [comment]
@Aaronb0117 The default recognizers will do some email address detection.  You'll need to write some test cases to see if that default implementation is good enough for you.
